/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Fase1;

import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author usuario
 */
public class Fase1 extends javax.swing.JFrame {
    Random generador = new Random();
    int letra;
    String letraImagen1="";
    String letraImagen2="";
    int aciertos=0;
    int numImagenesAcertar = 4;    
    /**
     * Creates new form Fase1
     */
    public Fase1() {
        initComponents();
        jToggleButton1.setEnabled(false);
        jToggleButton2.setEnabled(false);
        jToggleButton3.setEnabled(false);
        jToggleButton4.setEnabled(false);
        jToggleButton5.setEnabled(false);
        jToggleButton6.setEnabled(false);
        jToggleButton7.setEnabled(false);
        jToggleButton8.setEnabled(false);
        jToggleButton9.setEnabled(false);
        jToggleButton10.setEnabled(false);
        jToggleButton11.setEnabled(false);
        jToggleButton12.setEnabled(false);
        jToggleButton13.setEnabled(false);
        jToggleButton14.setEnabled(false);
        jToggleButton15.setEnabled(false);
        jToggleButton16.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelImagen1 = new javax.swing.JLabel();
        jLabelImagen3 = new javax.swing.JLabel();
        jLabelImagen4 = new javax.swing.JLabel();
        jLabelImagen2 = new javax.swing.JLabel();
        jLabelImagen6 = new javax.swing.JLabel();
        jLabelImagen5 = new javax.swing.JLabel();
        jLabelImagen7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelAciertos = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jLabelLvlUp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));

        jLabelImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jLabelImagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jLabelImagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jLabelImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jLabelImagen6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jLabelImagen5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jLabelImagen7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImagen1)
                .addGap(18, 18, 18)
                .addComponent(jLabelImagen2)
                .addGap(18, 18, 18)
                .addComponent(jLabelImagen3)
                .addGap(18, 18, 18)
                .addComponent(jLabelImagen4)
                .addGap(18, 18, 18)
                .addComponent(jLabelImagen5)
                .addGap(18, 18, 18)
                .addComponent(jLabelImagen6)
                .addGap(18, 18, 18)
                .addComponent(jLabelImagen7)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImagen7)
                    .addComponent(jLabelImagen5)
                    .addComponent(jLabelImagen6)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelImagen3)
                        .addComponent(jLabelImagen1)
                        .addComponent(jLabelImagen4)
                        .addComponent(jLabelImagen2, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));

        jButton1.setBackground(new java.awt.Color(179, 222, 244));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 153, 255));
        jButton1.setText("Empezar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(179, 222, 244));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 153, 255));
        jButton2.setText("Recordar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(179, 222, 244));
        jButton3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 153, 255));
        jButton3.setText("Comprobar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabelAciertos.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabelAciertos.setForeground(new java.awt.Color(51, 153, 255));
        jLabelAciertos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAciertos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aciertos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 10), new java.awt.Color(102, 153, 255))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAciertos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jLabelAciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jToggleButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jToggleButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jToggleButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jToggleButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jToggleButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jToggleButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jToggleButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        jToggleButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fase1/imagenes/Z.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton1)
                            .addComponent(jToggleButton11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jToggleButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToggleButton7))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jToggleButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToggleButton4))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jToggleButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jToggleButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton4)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton7)
                    .addComponent(jToggleButton5)
                    .addComponent(jToggleButton6)
                    .addComponent(jToggleButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton8)
                    .addComponent(jToggleButton9)
                    .addComponent(jToggleButton10)
                    .addComponent(jToggleButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton13)
                    .addComponent(jToggleButton14)
                    .addComponent(jToggleButton15)
                    .addComponent(jToggleButton16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLvlUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLvlUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //aciertos
        aciertos=0;
        //botones
        jToggleButton1.setEnabled(false);
        jToggleButton2.setEnabled(false);
        jToggleButton3.setEnabled(false);
        jToggleButton4.setEnabled(false);
        jToggleButton5.setEnabled(false);
        jToggleButton6.setEnabled(false);
        jToggleButton7.setEnabled(false);
        jToggleButton8.setEnabled(false);
        jToggleButton9.setEnabled(false);
        jToggleButton10.setEnabled(false);
        jToggleButton11.setEnabled(false);
        jToggleButton12.setEnabled(false);
        jToggleButton13.setEnabled(false);
        jToggleButton14.setEnabled(false);
        jToggleButton15.setEnabled(false);
        jToggleButton16.setEnabled(false);

        jToggleButton1.setSelected(false);
        jToggleButton2.setSelected(false);
        jToggleButton3.setSelected(false);
        jToggleButton4.setSelected(false);
        jToggleButton5.setSelected(false);
        jToggleButton6.setSelected(false);
        jToggleButton7.setSelected(false);
        jToggleButton8.setSelected(false);
        jToggleButton9.setSelected(false);
        jToggleButton10.setSelected(false);
        jToggleButton11.setSelected(false);
        jToggleButton12.setSelected(false);
        jToggleButton13.setSelected(false);
        jToggleButton14.setSelected(false);
        jToggleButton15.setSelected(false);
        jToggleButton16.setSelected(false);
        
        //generador numeros
        for(int i=0;i<8;i++){
                    letra = generador.nextInt(15)+65;
                    letraImagen1+=(char)letra;
        }
        //variables letras por separado
        char letra1 = letraImagen1.charAt(0);
        char letra2 = letraImagen1.charAt(1);
        char letra3 = letraImagen1.charAt(2);
        char letra4 = letraImagen1.charAt(3);
        char letra5 = letraImagen1.charAt(4);
        char letra6 = letraImagen1.charAt(5);
        char letra7 = letraImagen1.charAt(6);
        //System.out.println("Letras:" + letra1 + "-" + letra2 + "-" + letra3 + "-" + letra4+ "-" + letra5 + "-" + letra6 + "-" + letra7);  
        //comprobar repeticiones
        while(letra1 == letra2 || letra1 == letra3 || letra1 == letra4 || letra1 == letra5 || letra1 == letra6 || letra1 == letra7){
            letra = generador.nextInt(15)+65;
            letra1 = (char)letra;
        }
        while(letra2 == letra1 || letra2 == letra3 || letra2 == letra4 || letra2 == letra5 || letra2 == letra6 || letra2== letra7){
            letra = generador.nextInt(15)+65;
            letra2 = (char)letra;
        }
        while(letra3 == letra1 || letra3 == letra2 || letra3 == letra4 || letra3 == letra5 || letra3 == letra6 || letra3 == letra7){
            letra = generador.nextInt(15)+65;
            letra3 = (char)letra;
        }
        while(letra4 == letra1 || letra4 == letra2 || letra4 == letra3 || letra4 == letra5 || letra4 == letra6 || letra4 == letra7){
            letra = generador.nextInt(15)+65;
            letra4 = (char)letra;
        }
        while(letra5 == letra1 || letra5 == letra3 || letra5 == letra4 || letra2 == letra5 || letra5 == letra6 || letra5== letra7){
            letra = generador.nextInt(15)+65;
            letra5 = (char)letra;
        }
        while(letra6 == letra1 || letra6 == letra2 || letra6 == letra4 || letra6 == letra5 || letra3 == letra6 || letra6 == letra7){
            letra = generador.nextInt(15)+65;
            letra6 = (char)letra;
        }
        while(letra7 == letra1 || letra7 == letra2 || letra7 == letra3 || letra7 == letra5 || letra7 == letra6 || letra4 == letra7){
            letra = generador.nextInt(15)+65;
            letra7 = (char)letra;
        }
        //System.out.println("Letras 2:" + letra1 + "-" + letra2 + "-" + letra3 + "-" + letra4+ "-" + letra5 + "-" + letra6 + "-" + letra7); 
        try {
           switch(numImagenesAcertar){
               case 4:
                jLabelImagen1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra1 +".png"))));
                jLabelImagen2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra2 +".png"))));
                jLabelImagen3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra3 +".png"))));
                jLabelImagen4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra4 +".png"))));
                break;
               case 5:
                jLabelImagen1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra1 +".png"))));
                jLabelImagen2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra2 +".png"))));
                jLabelImagen3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra3 +".png"))));
                jLabelImagen4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra4 +".png"))));
                jLabelImagen5.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra5 +".png"))));
                break;
               case 6:
                jLabelImagen1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra1 +".png"))));
                jLabelImagen2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra2 +".png"))));
                jLabelImagen3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra3 +".png"))));
                jLabelImagen4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra4 +".png"))));
                jLabelImagen5.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra5 +".png"))));
                jLabelImagen6.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra6 +".png"))));
                break;
               case 7:
                jLabelImagen1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra1 +".png"))));
                jLabelImagen2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra2 +".png"))));
                jLabelImagen3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra3 +".png"))));
                jLabelImagen4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra4 +".png"))));
                jLabelImagen5.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra5 +".png"))));
                jLabelImagen6.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra6 +".png"))));
                jLabelImagen7.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra7 +".png"))));
                break;
           }
            jToggleButton1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));            
            jToggleButton2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));            
            jToggleButton3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));            
            jToggleButton4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));            
            jToggleButton5.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));            
            jToggleButton6.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));            
            jToggleButton7.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));            
            jToggleButton8.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));            
            jToggleButton9.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));            
            jToggleButton10.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));            
            jToggleButton11.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));            
            jToggleButton12.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));            
            jToggleButton13.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));            
            jToggleButton14.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));            
            jToggleButton15.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));            
            jToggleButton16.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));      
        } catch (IOException ex) {
           Logger.getLogger(Fase1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //aciertos
        aciertos=0;
        //botones ACTIVADOS
        jToggleButton1.setEnabled(true);
        jToggleButton2.setEnabled(true);
        jToggleButton3.setEnabled(true);
        jToggleButton4.setEnabled(true);
        jToggleButton5.setEnabled(true);
        jToggleButton6.setEnabled(true);
        jToggleButton7.setEnabled(true);
        jToggleButton8.setEnabled(true);
        jToggleButton9.setEnabled(true);
        jToggleButton10.setEnabled(true);
        jToggleButton11.setEnabled(true);
        jToggleButton12.setEnabled(true);
        jToggleButton13.setEnabled(true);
        jToggleButton14.setEnabled(true);
        jToggleButton15.setEnabled(true);
        jToggleButton16.setEnabled(true);
        //jLabel DESACTIVADOS
        try {
            jLabelImagen1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));
            jLabelImagen2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));
            jLabelImagen3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));
            jLabelImagen4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));
            jLabelImagen5.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));
            jLabelImagen6.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));
            jLabelImagen7.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/Z.png"))));
        } catch (IOException ex) {
            Logger.getLogger(Fase1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        for(int n=0;n<17;n++){   
             letra = generador.nextInt(15)+65;
             letraImagen2+=(char)letra;
        }
        //variables letras por separado
        char letra1 = letraImagen2.charAt(0);
        char letra2 = letraImagen2.charAt(1);
        char letra3 = letraImagen2.charAt(2);
        char letra4 = letraImagen2.charAt(3);
        char letra5 = letraImagen2.charAt(4);
        char letra6 = letraImagen2.charAt(5);
        char letra7 = letraImagen2.charAt(6);
        char letra8 = letraImagen2.charAt(7);
        char letra9 = letraImagen2.charAt(8);
        char letra10 = letraImagen2.charAt(9);
        char letra11 = letraImagen2.charAt(10);
        char letra12 = letraImagen2.charAt(11);
        char letra13 = letraImagen2.charAt(12);
        char letra14 = letraImagen2.charAt(13);
        char letra15 = letraImagen2.charAt(14);
        char letra16 = letraImagen2.charAt(15);
        //System.out.println("Letras3:" + letra1 + "-" + letra2 + "-" + letra3 + "-" + letra4+ letra5 + "-" + letra6 + "-" + letra7 + "-" + letra8+ letra9 + "-" + letra10 + "-" + letra11 + "-" + letra12+ letra13 + "-" + letra14 + "-" + letra15 + "-" + letra16);  
        //comprobar repeticiones
        if(letra1 == letra2 || letra1 == letra3 || letra1 == letra4 || letra1 == letra5 || letra1 == letra6 || letra1 == letra7 ||letra1 == letra8 || letra1 == letra9 || letra1 == letra10 || letra1 == letra11 || letra1 == letra12 || letra1 == letra13 || letra1 == letra14 || letra1 == letra15 || letra1 == letra16){
            letra = generador.nextInt(15)+65;
            letra1 = (char)letra;
        }
        if(letra2 == letra1 || letra2 == letra3 || letra2 == letra4 || letra2 == letra5 || letra2 == letra6 || letra2 == letra7 ||letra2 == letra8 || letra2 == letra9 || letra2 == letra10 || letra2 == letra11 || letra2 == letra12 || letra2 == letra13 || letra2 == letra14 || letra2 == letra15 || letra2 == letra16){
            letra = generador.nextInt(15)+65;
            letra2 = (char)letra;
        }
        if(letra3 == letra1 || letra3 == letra2 || letra3 == letra4 || letra3 == letra5 || letra3 == letra6 || letra3== letra7 ||letra3 == letra8 || letra3 == letra9 || letra3 == letra10 || letra3 == letra11 || letra3 == letra12 || letra3 == letra13 || letra3 == letra14 || letra3 == letra15 || letra3 == letra16){
            letra = generador.nextInt(15)+65;
            letra3 = (char)letra;
        }
        if(letra4 == letra1 || letra4 == letra2 || letra4 == letra3 || letra4 == letra5 || letra4 == letra6 || letra4 == letra7 ||letra4 == letra8 || letra4 == letra9 || letra4 == letra10 || letra4 == letra11 || letra4 == letra12 || letra4 == letra13 || letra4 == letra14 || letra4 == letra15 || letra4 == letra16){
            letra = generador.nextInt(15)+65;
            letra4 = (char)letra;
        }
        if(letra1 == letra5 || letra5 == letra3 || letra5 == letra4 || letra5 == letra2 || letra5 == letra6 || letra5 == letra7 ||letra5 == letra8 || letra5 == letra9 || letra5 == letra10 || letra5 == letra11 || letra5 == letra12 || letra5 == letra13 || letra5 == letra14 || letra5 == letra15 || letra5 == letra16){
            letra = generador.nextInt(15)+65;
            letra5 = (char)letra;
        }
        if(letra6 == letra1 || letra6 == letra3 || letra6 == letra4 || letra6 == letra5 || letra2 == letra6 || letra6 == letra7 ||letra6 == letra8 || letra6 == letra9 || letra6 == letra10 || letra6 == letra11 || letra6 == letra12 || letra6 == letra13 || letra6 == letra14 || letra6 == letra15 || letra6 == letra16){
            letra = generador.nextInt(15)+65;
            letra6 = (char)letra;
        }
        if(letra7 == letra1 || letra3 == letra7 || letra7 == letra4 || letra7 == letra5 || letra7 == letra6 || letra2== letra7 ||letra7 == letra8 || letra7 == letra9 || letra7 == letra10 || letra7 == letra11 || letra7 == letra12 || letra7 == letra13 || letra7 == letra14 || letra7 == letra15 || letra7 == letra16){
            letra = generador.nextInt(15)+65;
            letra7 = (char)letra;
        }
        if(letra8 == letra1 || letra4 == letra8 || letra8 == letra3 || letra8 == letra5 || letra8 == letra6 || letra8 == letra7 ||letra2 == letra8 || letra8 == letra9 || letra8 == letra10 || letra8 == letra11 || letra8 == letra12 || letra8 == letra13 || letra8 == letra14 || letra8 == letra15 || letra8 == letra16){
            letra = generador.nextInt(15)+65;
            letra8 = (char)letra;
        }
        if(letra1 == letra9 || letra9 == letra3 || letra9 == letra4 || letra9 == letra2 || letra9 == letra6 || letra9 == letra7 ||letra9 == letra8 || letra5 == letra9 || letra9 == letra10 || letra9 == letra11 || letra9 == letra12 || letra9 == letra13 || letra9 == letra14 || letra9 == letra15 || letra9 == letra16){
            letra = generador.nextInt(15)+65;
            letra9 = (char)letra;
        }
        if(letra10 == letra1 || letra10 == letra3 || letra10 == letra4 || letra10 == letra5 || letra2 == letra10 || letra10 == letra7 ||letra10 == letra8 || letra6 == letra10 || letra6 == letra10 || letra10== letra11 || letra10 == letra12 || letra10 == letra13 || letra10 == letra14 || letra10 == letra15 || letra10 == letra16){
            letra = generador.nextInt(15)+65;
            letra10 = (char)letra;
        }
        if(letra11 == letra1 || letra3 == letra11 || letra11 == letra4 || letra11 == letra5 || letra11 == letra6 || letra2== letra11 ||letra11 == letra8 || letra11 == letra9 || letra7 == letra10 || letra7 == letra11 || letra11 == letra12 || letra11 == letra13 || letra11 == letra14 || letra11 == letra15 || letra11 == letra16){
            letra = generador.nextInt(15)+65;
            letra11 = (char)letra;
        }
        if(letra12 == letra1 || letra4 == letra12 || letra12 == letra3 || letra12 == letra5 || letra12 == letra6 || letra12 == letra7 ||letra2 == letra12 || letra12 == letra9 || letra12 == letra10 || letra12 == letra11 || letra8 == letra12 || letra12 == letra13 || letra12 == letra14 || letra12 == letra15 || letra12 == letra16){
            letra = generador.nextInt(15)+65;
            letra12 = (char)letra;
        }
        if(letra1 == letra13 || letra13 == letra3 || letra13 == letra4 || letra13 == letra2 || letra13 == letra6 || letra13 == letra7 ||letra13 == letra8 || letra5 == letra13 || letra13 == letra10 || letra13 == letra11 || letra13 == letra12 || letra9 == letra13 || letra13 == letra14 || letra13 == letra15 || letra13 == letra16){
            letra = generador.nextInt(15)+65;
            letra13 = (char)letra;
        }
        if(letra14 == letra1 || letra14 == letra3 || letra14 == letra4 || letra14 == letra5 || letra2 == letra14 || letra14 == letra7 ||letra14 == letra8 || letra6 == letra14 || letra6 == letra14 || letra14== letra11 || letra14 == letra12 || letra14 == letra13 || letra10 == letra14 || letra14 == letra15 || letra14 == letra16){
            letra = generador.nextInt(15)+65;
            letra14 = (char)letra;
        }
        if(letra15 == letra1 || letra3 == letra15 || letra15 == letra4 || letra15 == letra5 || letra15 == letra6 || letra2== letra15 ||letra15 == letra8 || letra15 == letra9 || letra7 == letra15 || letra7 == letra15 || letra15 == letra12 || letra15 == letra13 || letra15 == letra14 || letra11 == letra15 || letra15 == letra16){
            letra = generador.nextInt(15)+65;
            letra15 = (char)letra;
        }
        if(letra16 == letra1 || letra4 == letra16 || letra16 == letra3 || letra16 == letra5 || letra16 == letra6 || letra16 == letra7 ||letra2 == letra16 || letra16 == letra9 || letra16 == letra10 || letra16 == letra11 || letra8 == letra16 || letra16 == letra13 || letra16 == letra14 || letra16 == letra15 || letra12 == letra16){
            letra = generador.nextInt(15)+65;
            letra16 = (char)letra;
        }
        //System.out.println("Letras 4:" + letra1 + "-" + letra2 + "-" + letra3 + "-" + letra4+ "-"+ letra5 + "-" + letra6 + "-" + letra7 + "-" + letra8+"-"+ letra9 + "-" + letra10 + "-" + letra11 + "-" + letra12+"-" +letra13 + "-" + letra14 + "-" + letra15 + "-" + letra16); 
        
        
        try {
            jToggleButton1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra1 +".png"))));
             jToggleButton2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra2 +".png"))));
             jToggleButton3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra3 +".png"))));
             jToggleButton4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra4 +".png"))));
             jToggleButton5.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra5 +".png"))));
             jToggleButton6.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra6 +".png"))));
             jToggleButton7.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra7 +".png"))));
             jToggleButton8.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra8 +".png"))));
             jToggleButton9.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra9 +".png"))));
             jToggleButton10.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra10 +".png"))));
             jToggleButton11.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra11 +".png"))));
             jToggleButton12.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra12 +".png"))));
             jToggleButton13.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra13 +".png"))));
             jToggleButton14.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra14 +".png"))));
             jToggleButton15.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra15 +".png"))));
             jToggleButton16.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/"+ letra16 +".png"))));
             
        } catch (IOException ex) {
                 Logger.getLogger(Fase1.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
               
        if(jToggleButton1.isSelected() && letraImagen1.indexOf(letraImagen2.charAt(0))!=-1){
             aciertos++;
        }else{
           jToggleButton1.setEnabled(false);
        }
        if(jToggleButton2.isSelected() && letraImagen1.indexOf(letraImagen2.charAt(1))!=-1){
            aciertos++;
        }else{
            jToggleButton2.setEnabled(false);
        }
        if(jToggleButton3.isSelected() && letraImagen1.indexOf(letraImagen2.charAt(2))!=-1){
            aciertos++;
        }else{
            jToggleButton3.setEnabled(false);
        }
        if(jToggleButton4.isSelected() && letraImagen1.indexOf(letraImagen2.charAt(3))!=-1){
            aciertos++;
        }else{
            jToggleButton4.setEnabled(false);
        }
        if(jToggleButton5.isSelected() && letraImagen1.indexOf(letraImagen2.charAt(4))!=-1){
            aciertos++;
        }else{
            jToggleButton5.setEnabled(false);
        }
        if(jToggleButton6.isSelected() && letraImagen1.indexOf(letraImagen2.charAt(5))!=-1){
            aciertos++;
        }else{
            jToggleButton6.setEnabled(false);
        }
        if(jToggleButton7.isSelected() && letraImagen1.indexOf(letraImagen2.charAt(6))!=-1){
            aciertos++;
        }else{
            jToggleButton7.setEnabled(false);
        }
        if(jToggleButton8.isSelected() && letraImagen1.indexOf(letraImagen2.charAt(7))!=-1){
           aciertos++;
        }else{
           jToggleButton8.setEnabled(false);
        }
        if(jToggleButton9.isSelected() && letraImagen1.indexOf(letraImagen2.charAt(8))!=-1){
            aciertos++;
        }else{
            jToggleButton9.setEnabled(false);
        }
        if(jToggleButton10.isSelected() && letraImagen1.indexOf(letraImagen2.charAt(9))!=-1){
            aciertos++;
        }else{
            jToggleButton10.setEnabled(false);
        }
        if(jToggleButton11.isSelected() && letraImagen1.indexOf(letraImagen2.charAt(10))!=-1){
            aciertos++;
        }else{
            jToggleButton11.setEnabled(false);
        }
        if(jToggleButton12.isSelected() && letraImagen1.indexOf(letraImagen2.charAt(11))!=-1){
            aciertos++;
        }else{
            jToggleButton12.setEnabled(false);
        }
        if(jToggleButton13.isSelected() && letraImagen1.indexOf(letraImagen2.charAt(12))!=-1){
            aciertos++;
        }else{
            jToggleButton13.setEnabled(false);
        }
        if(jToggleButton14.isSelected() && letraImagen1.indexOf(letraImagen2.charAt(13))!=-1){
            aciertos++;
        }else{
            jToggleButton14.setEnabled(false);
        }
        if(jToggleButton15.isSelected() && letraImagen1.indexOf(letraImagen2.charAt(14))!=-1){
            aciertos++;
        }else{
            jToggleButton15.setEnabled(false);
        }
        if(jToggleButton16.isSelected() && letraImagen1.indexOf(letraImagen2.charAt(15))!=-1){
            aciertos++;
        }else{
            jToggleButton16.setEnabled(false);
        }
        jLabelAciertos.setText("" + aciertos);
        if(aciertos>=4){
            try {
                jLabelLvlUp.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("imagenes/lvlup.jpg"))));
            } catch (IOException ex) {
                Logger.getLogger(Fase1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(aciertos == numImagenesAcertar && numImagenesAcertar<7) {
            numImagenesAcertar++;
            
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fase1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabelAciertos;
    private javax.swing.JLabel jLabelImagen1;
    private javax.swing.JLabel jLabelImagen2;
    private javax.swing.JLabel jLabelImagen3;
    private javax.swing.JLabel jLabelImagen4;
    private javax.swing.JLabel jLabelImagen5;
    private javax.swing.JLabel jLabelImagen6;
    private javax.swing.JLabel jLabelImagen7;
    private javax.swing.JLabel jLabelLvlUp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
